### ISSUE TITLE
[syncfusion_flutter_pdfviewer] text search giving wrong results for some pdfs

### ISSUE THREAD

**Issue by ritz-ch** [SyncfusionExamples/How-to-perform-text-search-using-flutter-pdf-viewer#2]
The text search functionality for syncfusion_flutter_pdfviewer is not working properly. For some pdfs, when the text search is applied, it highlights other words than the word I am searching. Also, when I search something it takes longer to give the search results . Please consider the screenshot  attached  below for the same. You can try checking search functionality for this pdf  http://112.196.1.221:9023/pdf/traffic_pub_gen19.pdf 
@ramkumarravy @suresh-mohan @ramkumarsync  .Can you guys please look into this as it's a little urgent!

![Screenshot_2021-07-28-11-18-46-369_com example guru](https://user-images.githubusercontent.com/60787872/127444670-16a2c591-95b3-4f7c-aefc-bb9facd2d0ec.jpg).

**Comment by deepika134** [comment]
Hi ritz-ch, 
 
Greetings from Syncfusion. 
 
We can reproduce the reported issue from our side. In provided document, we are getting improper text bounds details while loading into [PdfDocument](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfDocument-class.html) instance. We have forwarded this issue to the concern team and will update the further details on 3 August 2021. 

Regards, 
Deepika R

**Comment by ritz-ch** [comment]
Hi @deepika134 
Thanks for considering my question. I am looking forward to your update tomorrow.

**Comment by deepika134** [comment]
Hi ritz-ch,

We have confirmed that the reported issue "Text search gives the wrong result for some PDFs" is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on 24 August 2021 tentatively. The status of this issue can be tracked using the following link 
https://www.syncfusion.com/feedback/27578/textline-extraction-is-not-working-for-particular-pdf-document.

Regarding the delay in text search operation:
We are unable to provide the text search as Asynchronous. We have used text search methods from Syncfusion PDF package. Since, the requested support is yet to be given in that package, we are unable to do in our widget. As an alternative, we tried to use the [Isolate.spawn]( https://api.flutter.dev/flutter/dart-isolate/Isolate/spawn.html ) but, the spawn method allows static members and top-level function to make synchronous methods as asynchronous. Currently, we have no plans to implement this support and the status of the feature can be tracked using the following link https://www.syncfusion.com/feedback/21985/asynchronous-text-search

Regards,
Deepika R.

**Comment by achinverma** [comment]
@deepika134 , I am also getting the same issue. it highlights other words than the word I am searching. It would be great if can provide the solution before 12 Aug. I am stuck and I am not able to find any other package with the same feature.
Pls, can you help me with this?

**Comment by deepika134** [comment]
Hi @achinverma,

Citing your urgency, the fix for the reported issue “Text search gives the wrong result for some PDFs” will be included in our next weekly release which is estimated to be available on 17 August 2021.

Regards,
Deepika R

**Comment by ritz-ch** [comment]
Hi @deepika134,
Just wanted to know if we are on track and can we expect the release with fixes on 17 August 2021 for the above bug i.e., "Text search gives the wrong result for some PDFs" ?

**Comment by deepika134** [comment]
Hi ritz-ch,

Currently we are working on this. As we mentioned earlier, we will include the fix in our upcoming weekly NuGet release on August 17, 2021.

Regards,
Deepika

**Comment by ritz-ch** [comment]
Hi @deepika134 ,
I checked the latest version of syncfusion_flutter_pdfviewer plugin which is released today i.e., 17 August 2021. As mentioned by  you earlier that this release would contain fixes for the above bug i.e., "Text search gives the wrong result for some PDFs" ,  I checked this release and found out that it does not contain the solution to the above bug. Can you please confirm on the same? 
![image](https://user-images.githubusercontent.com/60787872/129722726-6f910efb-bd1f-425d-8263-c43faba8c6e5.png)

**Comment by Anand3595** [comment]
Hi @ritz-ch ,

Thanks for your patience.

We have included the fix for the reported issue "**Text search gives the wrong result for some PDFs**" in our latest weekly release with version [19.2.56-beta.1](https://pub.dev/packages/syncfusion_flutter_pdf/versions/19.2.56-beta.1).

Please let us know if you need any further assistance in this.

Regards,
Anand Panchamoorthi

**Comment by ritz-ch** [comment]
Hi @Anand3595 
@deepika134
I am using syncfusion_flutter_pdfviewer plugin as I have to load pdf from url  and open that pdf in my app and the bug I was encountering was in this plugin (if you read the issue on the top) and the fix you have given is for the different plugin i.e., syncfusion_flutter_pdf ...Now could you please help me and guide me on how to proceed further on this? Its really urgent!!

**Comment by deepika134** [comment]
Hi ritz-ch,

Sorry for the inconvenience. kindly upgrade to the latest version of Syncfusion Flutter packages to get the issue resolved. If you still facing the issue, kindly use the **flutter pub upgrade** command to upgrade the packages.

Note: please make sure the latest version of PDF package is referred in your application - https://pub.dev/packages/syncfusion_flutter_pdf/versions/19.2.56-beta.1

Regards,
Deepika R

**Comment by ritz-ch** [comment]
Hi @deepika134 
I have upgraded the syncfusion_flutter_pdfviewer package using flutter pub upgrade command but it does not solve the bug... I wanted the fix in this plugin but you have provided it in a different plugin.

![image](https://user-images.githubusercontent.com/60787872/129867806-e0837873-5855-480e-a1f7-31a1eb5f20b1.png)

**Comment by dillibabun** [comment]
Hi @ritz-ch ,

We have used the Syncfusion Flutter PDF package to retrieve the text bounds for text selection and search functionality. As the text search provided by Syncfusion Flutter PDF worked incorrectly for the given document, we have reported the issue to the concerned team internally. Now, Syncfusion Flutter PDF has resolved the issue and included the issue fix in the latest package. So, kindly upgrade that package to resolve the issue at your end.

Please find the video illustration of the issue fix in the latest package and the sample [here](https://www.syncfusion.com/downloads/support/directtrac/general/ze/Output-474660062.zip).

Regards,
Dilli babu

**Comment by ritz-ch** [comment]
@dillibabun 
I am a bit late on replying. The issue is resolved.
Thank you!
